version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: aws-partitions
    versions:
    - 1.446.0
    - 1.447.0
    - 1.448.0
  - dependency-name: aws-sdk-ec2
    versions:
    - 1.234.0
  - dependency-name: loofah
    versions:
    - 2.6.0
    - 2.9.0
    - 2.9.1
  - dependency-name: aws-eventstream
    versions:
    - 1.1.0
    - 1.1.1
  - dependency-name: aws-sigv4
    versions:
    - 1.2.2
    - 1.2.3
  - dependency-name: spring
    versions:
    - 2.1.0
    - 2.1.1
  - dependency-name: rails_admin
    versions:
    - 1.4.3
  - dependency-name: jquery-rails
    versions:
    - 4.3.4
  - dependency-name: puma
    versions:
    - 3.12.6
  - dependency-name: nokogiri
    versions:
    - 1.10.8
    - 1.11.0
  - dependency-name: devise
    versions:
    - 4.7.1
  - dependency-name: json
    versions:
    - 2.3.1
    - 2.5.1
  - dependency-name: rack
    versions:
    - 2.2.3
  - dependency-name: kaminari
    versions:
    - 1.2.1
  - dependency-name: rubyzip
    versions:
    - 1.3.0
  - dependency-name: rake
    versions:
    - 12.3.3
  - dependency-name: net-scp
    versions:
    - 3.0.0
  - dependency-name: brakeman
    versions:
    - 4.9.0
  - dependency-name: net-ssh
    versions:
    - 6.1.0
  - dependency-name: websocket-extensions
    versions:
    - 0.1.5
  - dependency-name: mixlib-cli
    versions:
    - 2.1.6
  - dependency-name: rack-pjax
    versions:
    - 1.1.0
