# BASED ON
# https://blog.codeminer42.com/zero-to-up-and-running-a-rails-project-only-using-docker-20467e15f1be/

# Specify the Docker image to use as a base:
FROM ruby:RUBY_VERSION-stretch

ENV DEBIAN_FRONTEND=noninteractive \
    NODE_VERSION=14.16.0 \
    PHANTOM_JS=phantomjs-2.1.1-linux-x86_64

# 4th line below: packages needed for this particular Rails app
# 5th and 6th lines below: packages needed for PhantomJS (needed for this particular Rails app)
RUN sed -i '/deb-src/d' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y build-essential tree graphviz nodejs && \
    apt-get install -y libnotify4 libgtkmm* && \
    apt-get install -y libffi-dev build-essential chrpath libssl-dev libxft-dev && \
    apt-get install -y libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev

RUN curl -sSL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" | tar xfJ - -C /usr/local --strip-components=1 && \
    npm install npm -g

# Install PhantomJS using procedure from
# https://gist.github.com/telbiyski/ec56a92d7114b8631c906c18064ce620
RUN wget https://github.com/Medium/phantomjs/releases/download/v2.1.1/$PHANTOM_JS.tar.bz2 && \
  tar xvjf $PHANTOM_JS.tar.bz2 && \
  mv $PHANTOM_JS /usr/local/share && \
  ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin && \
  phantomjs --version

RUN useradd -m -s /bin/bash -u 1000 winner
USER winner

WORKDIR /home/winner/myapp
