#!/bin/bash

mkdir -p notes

file_he='notes/1-file_list-helpers.txt'
file_mo='notes/1-file_list-models.txt'
file_co='notes/1-file_list-controllers.txt'
file_vi='notes/1-file_list-views.txt'

echo '-------------------------------'
echo 'sudo service postgresql restart'
sudo service postgresql restart
wait

echo '-----------------------------'
echo 'bundle exec annotate --routes'
bundle exec annotate --routes

echo '--------------------'
echo 'bundle exec annotate'
bundle exec annotate

echo '------------------------------------'
echo 'Listing the helper files in the file'
echo $file_he
echo 'This file was AUTOMATICALLY generated by the outline.sh script.' > $file_he
echo '-------------------' >> $file_he
echo 'HELPERS' >> $file_he
tree test/helpers >> $file_he
echo '' >> $file_he
tree spec/helpers >> $file_he
echo '' >> $file_he
tree app/helpers >> $file_he
echo '' >> $file_he

echo '-------------------------------'
echo 'Listing the model files in file'
echo $file_mo
echo 'This file was AUTOMATICALLY generated by the outline.sh script.' > $file_mo
echo '------' >> $file_mo
echo 'MODELS' >> $file_mo
tree test/models >> $file_mo
echo '' >> $file_mo
tree spec/models >> $file_mo
echo '' >> $file_mo
tree test/fixtures >> $file_mo
echo '' >> $file_mo
tree app/models >> $file_mo

echo 'This file was AUTOMATICALLY generated by the outline.sh script.' > $file_co
echo '-----------' >> $file_co
echo 'CONTROLLERS' >> $file_co
tree test/controllers >> $file_co
echo '' >> $file_co
tree spec/controllers >> $file_co
echo '' >> $file_co
tree app/controllers >> $file_co

echo 'This file was AUTOMATICALLY generated by the outline.sh script.' > $file_vi
echo '---------------------------' >> $file_vi
echo 'VIEWS AND INTEGRATION TESTS' >> $file_vi
echo '' >> $file_vi
echo '----------------' >> $file_vi
echo 'config/routes.rb' >> $file_vi
cat config/routes.rb >> $file_vi
echo '----------------' >> $file_vi
tree test/integration >> $file_vi
echo '' >> $file_vi
tree spec/features >> $file_vi
echo '' >> $file_vi
tree app/views >> $file_vi

echo 'FINISHED compiling the list of files that make up the MVC structure'
echo '-------------------------------------------------------------------'

echo '******************************'
echo 'outline-short.sh OUTPUT FILES:'
echo $file_he
echo $file_mo
echo $file_co
echo $file_vi
echo
