#!/bin/bash
set +e
echo '----------------------------------------------------------------------------------------'
echo 'mkdir -p /home/winner/bundle/vendor && chown -R winner:winner /home/winner/bundle/vendor'
docker-compose run --rm -u root web bash -c 'mkdir -p /home/winner/bundle/vendor && chown -R winner:winner /home/winner/bundle/vendor'

set -e
echo '---------------------'
echo 'BEGIN: bundle install'
echo '---------------------'
docker/run bundle install
echo '-------------------'
echo 'END: bundle install'
echo '-------------------'
