default: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  username: adopta

development:
  <<: *default
  database: adopta_development

test:
  <<: *default
  database: adopta_test

production:
  <<: *default
  database: adopta_production
  username: ENV['DATABASE_USERNAME']
  password: ENV['DATABASE_PASSWORD']
