default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: adopta
  password:

development:
  <<: *default
  database: adopta_development

test:
  <<: *default
  database: adopta_test

production:
  <<: *default
  database: adopta_production
