default: &default
  adapter: postgresql
  encoding: unicode
  username: adopta
  pool: 5

development:
  <<: *default
  database: adopta_development

test:
  <<: *default
  database: adopta_test

production:
  <<: *default
  database: adopta_production
  username: ENV['DATABASE_USERNAME']
  password: ENV['DATABASE_PASSWORD']
